apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-app
  name: frontend-ihm
  labels:
    app: frontend-ihm
spec:
  selector:
    matchLabels:
      app: frontend-ihm
  template:
    metadata:
      labels:
        app: frontend-ihm
    spec:
      imagePullSecrets:
        - name: dockerSecret
      containers:
        - name: frontend-ihm
          image: system.registry.eneci.net/oci-frontend:latest  #Change this image according your env
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-app
  name: frontend-ihm-svc
spec:
  type: NodePort
  selector:
    app: frontend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30401
