apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-app
  name: backend-ihm
  labels:
    app: backend-ihm
spec:
  selector:
    matchLabels:
      app: backend-ihm
  template:
    metadata:
      labels:
        app: backend-ihm
    spec:
      # imagePullSecrets:
      #   - name: dockersecret
      containers:
        - name: backend-ihm
          image: dykoffy/oci-backend:latest #Change this image according your env
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 800m
              memory: 512Mi
          env:
            - name: MINIO_ENDPOINT
              value: "10.242.33.176"
            - name: MINIO_PORT
              value: "9000" #Change this value according your env
            - name: MINIO_ACCESS_KEY
              value: motower #Change this value according your env
            - name: MINIO_SECRET_KEY
              value: 3Gkbd2QoRrhyvQyyVobQeBHJ6u3CHdgdO3MXrF1k #Change this value according your env
            - name: MINIO_BUCKETNAME
              value: motower
            - name: DATABASE_URL
              value: postgresql://motower:6Sfa6MTpt96dY2D9Jv5c@postgres-postgresql:5432/ihm_db?schema=public
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-app
  name: backend-ihm-svc
spec:
  type: NodePort
  selector:
    app: backend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30400
