apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: oci-ihm
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "db"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: ihm_db
        - name: POSTGRES_USER
          value: ihm-user
        - name: POSTGRES_PASSWORD
          value: "123456789"
        - name: PGDATA
          value: /var/lib/postgresql/data
        volumeMounts:
        - name: postgresql
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgresql
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: oci-ihm
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30288
      targetPort: 5432