apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-app
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: KEYCLOAK_DATABASE_VENDOR
              value: postgresql
            - name: KEYCLOAK_DATABASE_HOST
              value: keycloak-postgres-postgresql
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_NAME
              value: keycloak
            - name: KEYCLOAK_DATABASE_USER
              value: keycloak
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: 6Sfa6MTpt96dY2D9Jv5c
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: 6Sfa6MTpt96dY2D9Jv5c
          ports:
            - containerPort: 8080
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-app
  name: keycloak-svc
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30402
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30403
