fullnameOverride: keycloak
auth:
  adminUser: admin
  adminPassword: 6Sfa6MTpt96dY2D9Jv5c
postgresql:
  enabled: true
  postgresqlUsername: keycloak
  postgresqlPassword: 6Sfa6MTpt96dY2D9Jv5c
  postgresqlDatabase: keycloak
proxyAddressForwarding: true
service:
  type: NodePort
  nodePorts:
    http: "30402"
    https: "30403"
resources:
  requests:
    cpu: "400m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"