global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  postgresql:
    auth:
      postgresPassword: ""
      username: "motower"
      password: "6Sfa6MTpt96dY2D9Jv5c"
      database: "ihm_db"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
primary:
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 256Mi